### ISSUE TITLE
Placeholder filename ideas

### ISSUE THREAD

**Issue by Fearce** [TheXorog/BeatRecorder#12]
Hi, love this application. Had a few filename ideas:

- FC or no
- Bad cuts ( misses alone feels useless since bad cuts are not included )
- Star difficulty

**Comment by TheXorog** [comment]
I will most likely be able to implement the first two. The star difficulty is more difficult because DataPuller is quite unreliable when it comes to getting the BeatSaver (or ScoreSaber, not sure) info for each song. At least, when i did the initial implementation.

**Comment by TheXorog** [comment]
Oh and the other supported mod http-status doesn't give me any beatsaber/scoresaber info about the song at all.

**Comment by TheXorog** [comment]
I have to scrap bad cuts as well, sadly. Only Http-Status provides the info separately, unlike the other mods. Misses are supposed to include Bad Cuts, Missed Notes and Bombs Hit. I don't know why but sometimes some are simply not tracked when using DataPuller. I read that Beat Saber changed something on how it processes the current song state in some recent-ish update so i believe it has to something with that. Although this might've been fixed with the commit https://github.com/TheXorog/BeatRecorder/commit/4e95876aba7112ce941c3ce24cb89a8a0ce50c65.



To the last remaining placeholder: I simply made it so the `<misses>` Placeholder gets replaced with `FC` if you didn't miss: https://github.com/TheXorog/BeatRecorder/commit/b1666e2a952038c4b5f290dde484cd62a66a598c. Not a perfect solution, but the best i could come up with since again, not all mods provide the info required to properly check if it's a fc.

**Comment by TheXorog** [comment]
The one thing that i was able to implement from this issue is now in [2.0](https://github.com/TheXorog/BeatRecorder/releases/tag/2.0). I'm sorry i couldn't implement them all.
